name: Docker Image CI

on:
  push:
    branches: [ main, dev, staging ]
  pull_request:
    branches: [ main, dev, staging ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create env file for staging
      if: github.ref == 'refs/heads/staging'
      run: echo "${{ secrets.STAGING_ENV }}" > .env
    - name: Create env file for production
      if: github.ref == 'refs/heads/main'
      run: echo "${{ secrets.PROD_ENV }}" > .env
    - name: Build Docker image
      run: docker build -t flower-classification:latest .
    - name: Test Docker image (healthcheck)
      run: |
        docker run -d --name flower-api -p 8000:8000 flower-classification:latest
        sleep 3
        curl -f http://localhost:8000/health
        docker logs flower-api
        docker rm -f flower-api