name: Docker Image CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t flower-classification:latest .
    - name: Test Docker image
      run: |
        docker run --rm flower-classification:latest python -c "import src; print('Import test passed')"