name: Python Application CI

on:
  push:
    branches: [ main, dev, staging ]
  pull_request:
    branches: [ main, dev, staging ]

jobs:
  lint-and-format:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: pip install -r requirements.txt
    - run: black --check src/ tests/
    - run: isort --check-only src/ tests/
    - run: flake8 src/ tests/

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint-and-format
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Configure MLflow to DagsHub
      run: |
        if [ -n "${{ secrets.DAGSHUB_USERNAME }}" ] && [ -n "${{ secrets.DAGSHUB_TOKEN }}" ]; then
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/flower-classification-project.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=${{ secrets.DAGSHUB_USERNAME }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV
        else
          echo "DagsHub secrets not set, skipping MLflow config"
        fi
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE/src:$GITHUB_WORKSPACE" >> $GITHUB_ENV
    - name: Run tests
      run: python -m pytest tests/ -v